apiVersion: apps/v1
kind: Deployment
metadata:
  name: ge-server
  labels:
    app: ge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ge-server
  template:
    metadata:
      labels:
        app: ge-server
    spec:
      containers:
        - name: ge-server
          image: pairate/ge-rest:0.0.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: ge-data
              mountPath: /ge
          imagePullPolicy: Always
      volumes:
        - name: ge-data
          persistentVolumeClaim:
            claimName: ge-pvc
