apiVersion: v1
kind: Pod
metadata:
  name: ge-init
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: ge-data
      mountPath: /ge
  volumes:
  - name: ge-data
    persistentVolumeClaim:
      claimName: ge-pvc
